# -*- coding: utf-8 -*-
"""
Builds dentistry.html — «Dentistry Made Visual» kit (US).

It is the English sister of the Italian /odontoiatria landing: same sections
in the same order. What it does NOT take from Italy is the shell — the head,
the CSS, the carousels, the accordions and the footer all come out of
ekg.html, like every other landing in this repo, so a CSS fix on the site
reaches this page by regenerating it.

WHO IT TALKS TO. Not «dental assistants» and nothing else. The book is
dentistry explained with drawings, and the reader is anyone sitting beside
the chair who needs to understand what is happening: assistants,
hygienists and first-year students. The book project's struttura.py says
this at length, and it is the reason the title is not «Dental Assisting
Made Visual».

WHAT IS AMERICAN ABOUT IT. The signature page charts in the Universal
system (1-32, A-T), the infection control part is framed on CDC and OSHA,
and the first pull-out table sets Universal, FDI and Palmer side by side —
which is what makes the book usable outside the United States too. Copy is
American English throughout: sterilization, color, center, labeled,
anesthetic, recognize.

THE TABLE OF CONTENTS IS NOT TYPED HERE. It is read from the book's own
struttura.py, so moving a chapter in the book moves it on the landing.

PRICE AND CHECKOUT come from the live checkout page, opened in a browser:
the product there is «Illustrated Dentistry Kit» at US$ 27 with an anchor
value of US$ 91, so those are the numbers and the kit name used here. The
per-book values are the Italian kit's own split rounded to the dollar —
they are not list prices, and the comment printed at the top of the HTML
says so. The two checkout bumps ($14.50, $7.90) are not on the landing.

Images are built separately and already exist:
  mockups/dentistry/{hero,combo,bonus-trays,bonus-emerg,questo,og}
  anteprime/dentistry_01..07.webp
The seven previews are these pages of Dentistry-Made-Visual.pdf:
  01 p.12 num_us · 02 p.18 lay_a · 03 p.34 kit_a · 04 p.41 t_rest_a
  05 p.52 comp_a · 06 p.70 chain_a · 07 p.23 nerves

  python tools/make_dentistry.py
"""
import html
import json
import os
import sys

SITO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LIBRO = r"C:\Users\lucag\Desktop\CLAUDE\Infoproductos\Dental-US"
sys.path.insert(0, LIBRO)
import struttura as S  # noqa: E402

TITLE = "Dentistry Made Visual"
SLUG = "dentistry"
URL = f"https://www.medicalstudylab.com/{SLUG}"
IMG = f"https://www.medicalstudylab.com/mockups/{SLUG}"

# ---------------------------------------------------------------------------
# PREZZO E CHECKOUT: PRESI DAL CHECKOUT VERO, APERTO NEL BROWSER.
#
# Il prodotto nel checkout si chiama «Illustrated Dentistry Kit» e mostra
# US$ 27 con un valore d'ancora di US$ 91. Il nome e le due cifre sulla
# landing sono quelle: il compratore deve leggere lo stesso numero da
# entrambe le parti, altrimenti il clic sul bottone e' il punto in cui se
# ne accorge. Gli altri importi che il checkout mostra ($14,50 e $7,90)
# sono i bump e non stanno qui.
PRICE_N = 27
TOTAL_N = 91
PRICE = f"${PRICE_N}"
TOTAL = f"${TOTAL_N}"
SAVINGS = f"${TOTAL_N - PRICE_N}"
CHECKOUT = ("https://checkout.medicalstudylab.com/checkout/"
            "illustrated-dentistry-kit")
KIT = "Illustrated Dentistry Kit"

# I tre valori di riga. Il checkout da' il totale (91) e il prezzo (27), non
# come il totale si divide fra i tre volumi. La divisione e' quella che Luca
# ha già scelto per lo STESSO kit in italiano (odontoiatria: 17,90 il bonus
# dei vassoi, 14,90 quello delle emergenze, il resto il volume principale),
# arrotondata al dollaro in modo che la somma faccia esattamente 91. Non
# sono numeri inventati e non sono prezzi di listino: se Luca vuole un'altra
# divisione, si cambiano qui e basta rigenerare.
VAL_B1_N, VAL_B2_N = 18, 15
VAL_MAIN_N = TOTAL_N - VAL_B1_N - VAL_B2_N      # 58
VAL_MAIN, VAL_B1, VAL_B2 = f"${VAL_MAIN_N}", f"${VAL_B1_N}", f"${VAL_B2_N}"
assert VAL_MAIN_N + VAL_B1_N + VAL_B2_N == TOTAL_N

AVVISO = f"""<!--
  ===========================================================================
  Generated by tools/make_dentistry.py — DO NOT HAND-EDIT THIS FILE.
  Edit the script and run `python tools/make_dentistry.py`.

  Price and checkout come from the live checkout page, opened in a browser:
  «Illustrated Dentistry Kit», US$ {PRICE_N}, anchor value US$ {TOTAL_N}.
    checkout : {CHECKOUT}
    price    : {PRICE} · total value {TOTAL} · you save {SAVINGS}

  The per-book values ({VAL_MAIN} / {VAL_B1} / {VAL_B2}) are NOT list prices:
  the two bonus books have none yet. They are the split of the Italian kit
  for the same three volumes, rounded to the dollar so they add up to
  {TOTAL} exactly. Change VAL_B1_N / VAL_B2_N in the script to re-split.

  robots is noindex, nofollow — same as anatomy.html, abg.html, dosage.html
  and ekg-ems.html. These are paid-traffic landings; only ekg.html and
  ecg-uk.html are indexed. Flip it in the script if that changes.
  ===========================================================================
-->
"""

# Il pixel di odontoiatria. NON sostituisce il principale di Med Study Lab
# (1369545011992472), che e' gia' inizializzato nell'head di ekg.html e lo
# ereditano tutte le landing: una campagna che ottimizza su questo pixel
# vedrebbe gli acquisti e mai la visita, cioe' imparerebbe su mezzo imbuto.
# «trackSingle» e non «track»: il PageView del pixel principale e' gia'
# partito, un secondo «track» lo conterebbe due volte. Gli eventi dopo
# (ViewContent, InitiateCheckout) usano «track» e partono per tutti e due.
PIXEL = "1616069600057839"
PIXEL_JS = f"""
  <!-- Meta Pixel — dentistry (added to the main one, not instead of it) -->
  <script>
    fbq('init','{PIXEL}');
    fbq('trackSingle','{PIXEL}','PageView');
  </script>
  <noscript><img height="1" width="1" style="display:none" alt=""
    src="https://www.facebook.com/tr?id={PIXEL}&ev=PageView&noscript=1"></noscript>

"""

B1 = "Tray Setups Made Visual"
B2 = "Chairside Emergencies Made Visual"

PAGES = S.TOTALE                                   # 86
N_PARTS = len(S.PARTI)                             # 4
N_CHAP = sum(len(c) for *_r, c in S.PARTI)         # 43


# --- il sommario, calcolato dal libro ------------------------------------
def part_from(num):
    """La prima pagina di contenuto: il divisore piu' uno."""
    return S.folio(S.DIVISORI[num]) + 1


def part_to(num):
    """L'ultima pagina dell'ultimo capitolo della parte."""
    return S.folio([c for n, _t, _s, c in S.PARTI if n == num][0][-1][1][-1])


# Le quattro tavole da staccare, col titolo che si legge in pagina.
CLOSING = [("The three numbering systems, tooth by tooth", "tav_numbering"),
           ("The four trays, side by side", "tav_trays"),
           ("Setting and working times", "tav_times"),
           ("The infection control chain, step by step", "tav_chain")]

BLURB = {
    "I": "The names, the numbers and how a tooth is actually built: the "
         "vocabulary that makes everything the dentist calls out loud "
         "readable &mdash; charted in the Universal system, with FDI and "
         "Palmer beside it.",
    "II": "Recognize an instrument at a glance, pass it without looking, and "
          "set the right tray for the appointment that is on the schedule.",
    "III": "Composite, cements, impressions, stone: what gets used, in what "
           "order, and how much time you have before it sets.",
    "IV": "The chain from the dirty tray to the wrapped instrument, the "
          "autoclave and the spore test &mdash; the CDC and OSHA part that "
          "every exam asks about.",
}

# Le sette anteprime: pagine vere del libro. L'ordine alterna la forma —
# una tabella, una sezione, un gruppo di oggetti, un vassoio, una sequenza,
# una catena, una mappa. Sette variazioni della stessa cosa si scorrono
# senza fermarsi.
SAMPLES = [
    ("dentistry_01", "Every tooth has a number: the Universal system, "
                     "quadrant by quadrant", 1557),
    ("dentistry_02", "A tooth is built in layers, and decay crosses them "
                     "one at a time", 1473),
    ("dentistry_03", "The exam kit: four instruments, and what each one is "
                     "for", 1473),
    ("dentistry_04", "The tray for a filling, laid out in the order it is "
                     "used", 1473),
    ("dentistry_05", "Etch, bond, place: composite in the order it happens",
     1473),
    ("dentistry_06", "From the dirty tray to the wrapped instrument", 1473),
    ("dentistry_07", "Where the nerves run, and why anesthetic takes here "
                     "and not there", 1473),
]

FAQ = [
    ("How will I receive the material?",
     f"Right after purchase you get an automatic email with all three books: "
     f"{TITLE}, {B1} and {B2}. They are high-resolution PDFs, ready to "
     f"download, print or read on any device."),
    ("Is this a one-time payment or a subscription?",
     f"One-time payment of {PRICE}. No installments, no recurring charges, "
     f"no surprises. You pay once and the material is yours forever."),
    ("Do I need experience, or can I start from zero?",
     "You can start from zero. Part I gives you the names of the teeth, the "
     "numbering and the surfaces &mdash; the vocabulary the dentist calls "
     "out loud. If you have been chairside for months already, skip to the "
     "part you need and use the four pull-out tables."),
    ("Is this a book for dentists?",
     "No, and it says so on its own page 3: it is written for the person on "
     "the other side of the chair. Dental assistants, hygienists and "
     "first-year students. There are no diagnoses and no treatment plans in "
     "it &mdash; those stay with the dentist."),
    ("Will it help with a dental assisting program or certification?",
     "It covers the subjects a program teaches and the office uses every "
     "day: instruments, materials, tray setups and the infection control "
     "chain on CDC and OSHA lines. It is not a course and it awards no "
     "credential: it is the illustrated material that goes alongside what "
     "you are already doing."),
    ("Does the emergency bonus replace a BLS or CPR course?",
     "No, and the bonus says so on its first page. Resuscitation is learned "
     "with your hands, on a manikin, with an instructor. That book covers "
     "what comes before: recognizing it fast and doing the right things "
     "while the person who takes over is on the way. Three verbs only "
     "&mdash; recognize, call, assist."),
    ("Does it work outside the United States?",
     "Yes, and that is deliberate. The book charts in the Universal system "
     "because that is what a US office uses, but the second page of that "
     "chapter covers FDI and Palmer, and the first pull-out table sets all "
     "three side by side. Teeth, instruments and materials are the same "
     "everywhere; infection control is written on CDC and OSHA lines, so "
     "check your own regulator for the paperwork."),
    ("Can I print the material?",
     "Yes, for personal use and without limits. The PDFs are high "
     "resolution, and the four pull-out tables are made to be printed and "
     "taped up next to the sterilizer."),
]

CHECK_SVG = ('<span class="db-check"><svg viewBox="0 0 24 24">'
             '<polyline points="20 6 9 17 4 12"/></svg></span>')

DESCR = (f"Teeth, instruments, materials and sterilization in {PAGES} "
         f"illustrated pages, one topic per page, plus 2 bonus books. "
         f"{PRICE}, 30-day guarantee.")


def head(tpl_head):
    h = tpl_head
    rep = [
        ("<title>Reading EKGs Made Visual: the illustrated guide on real "
         "tracings | Med Study Lab</title>",
         f"<title>{TITLE}: the easiest way to understand dentistry, fully "
         f"illustrated | Med Study Lab</title>"),
        ('content="Rhythm, arrhythmias, blocks, MI and electrolytes in 68 '
         'illustrated pages on real EKGs, plus 2 bonus books. $27, 30-day '
         'guarantee."', f'content="{DESCR}"'),
        ('<meta name="robots" content="index, follow">',
         '<meta name="robots" content="noindex, nofollow">'),
        ('  <link rel="alternate" hreflang="en" '
         'href="https://www.medicalstudylab.com/">\n', ''),
        ('href="https://www.medicalstudylab.com/ekg"', f'href="{URL}"'),
        ('content="https://www.medicalstudylab.com/ekg"', f'content="{URL}"'),
        ('content="Reading EKGs Made Visual | Med Study Lab"',
         f'content="{TITLE} | Med Study Lab"'),
        ('content="Read an EKG without panicking: an 8-step method on real '
         'tracings, explained with pictures."',
         'content="The easiest way to understand dentistry, fully '
         'illustrated: teeth, instruments, materials and sterilization, '
         'one topic per page."'),
        ("https://www.medicalstudylab.com/mockups/ekg/og.jpg", f"{IMG}/og.jpg"),
        ('content="Reading EKGs Made Visual — Med Study Lab"',
         f'content="{TITLE} — Med Study Lab"'),
        ('content="68 illustrated pages on real EKGs + 2 bonus books."',
         f'content="{PAGES} illustrated pages for the person beside the '
         f'chair + 2 bonus books."'),
    ]
    for a, b in rep:
        assert a in h, a[:70]
        h = h.replace(a, b)
    s = h.index('<script type="application/ld+json">')
    e = h.index("</script>", s) + len("</script>")
    ld = {"@context": "https://schema.org", "@graph": [
        {"@type": "Product", "name": KIT,
         "brand": {"@type": "Brand", "name": "Med Study Lab"},
         "description": f"{PAGES} illustrated pages of dentistry for the "
                        "people beside the chair: the teeth and all three "
                        "numbering systems, the instruments and the trays, "
                        "the materials and their setting times, and the "
                        "infection control chain on CDC and OSHA lines. "
                        "With two bonus books.",
         "image": f"{IMG}/hero.webp",
         "offers": {"@type": "Offer", "price": str(PRICE_N),
                    "priceCurrency": "USD",
                    "availability": "https://schema.org/InStock",
                    "url": CHECKOUT,
                    "hasMerchantReturnPolicy": {
                        "@type": "MerchantReturnPolicy",
                        "returnPolicyCategory":
                            "https://schema.org/MerchantReturnFiniteReturnWindow",
                        "merchantReturnDays": 30,
                        "applicableCountry": "US"}}},
        {"@type": "FAQPage", "mainEntity": [
            {"@type": "Question", "name": html.unescape(q),
             "acceptedAnswer": {"@type": "Answer", "text": html.unescape(a)}}
            for q, a in FAQ]}]}
    h = (h[:s] + '<script type="application/ld+json">\n'
         + json.dumps(ld, ensure_ascii=False) + "\n  </script>" + h[e:])
    # il pixel di odontoiatria in coda all'head, dopo quello principale
    i = h.rindex("</head>")
    h = h[:i] + PIXEL_JS + h[i:]
    # L'avviso va DOPO <meta charset>, non in cima al file. Messo subito
    # dopo il doctype spingeva il charset oltre i primi 1024 byte, che e'
    # la finestra in cui il browser lo cerca: senza, la pagina si leggeva
    # in latin-1 e le cinque stelle dell'hero uscivano «â˜…â˜…â˜…».
    cs = '<meta charset="UTF-8">'
    j = h.index(cs) + len(cs) + 1
    return h[:j] + AVVISO + h[j:]


def body():
    acc = []
    for i, (num, name, _sub, chapters) in enumerate(S.PARTI, 1):
        items = "".join(f"<li>{t}</li>" for t, _k in chapters)
        acc.append(f'''        <div class="subject-item" data-open="false" role="listitem">
          <button class="subject-summary" type="button" aria-expanded="false" aria-controls="subj-content-{i}">
            <span class="subject-num" aria-hidden="true">{num}</span>
            <span class="subject-title">{name} <em style="font-style:normal;opacity:.6;font-weight:600">&middot; pp. {part_from(num)}-{part_to(num)}</em></span>
            <span class="subject-icon" aria-hidden="true"></span>
          </button>
          <div class="subject-content" id="subj-content-{i}" role="region">
            <div class="subject-content-inner"><ul class="subject-content-list">{items}</ul></div>
          </div>
        </div>''')
    end = "".join(f"<li>{t} &mdash; p. {S.folio(k)}</li>" for t, k in CLOSING)
    acc.append(f'''        <div class="subject-item" data-open="false" role="listitem">
          <button class="subject-summary" type="button" aria-expanded="false" aria-controls="subj-content-9">
            <span class="subject-num" aria-hidden="true">&middot;</span>
            <span class="subject-title">At the end: the pull-out tables <em style="font-style:normal;opacity:.6;font-weight:600">&middot; pp. {S.folio(CLOSING[0][1])}-{PAGES}</em></span>
            <span class="subject-icon" aria-hidden="true"></span>
          </button>
          <div class="subject-content" id="subj-content-9" role="region">
            <div class="subject-content-inner"><ul class="subject-content-list">{end}</ul></div>
          </div>
        </div>''')

    topics = []
    for num, name, _sub, _c in S.PARTI:
        topics.append(f'''        <div class="topic-item">
          <span class="topic-num">{num}</span>
          <div>
            <span class="topic-pages">pp. {part_from(num)}&ndash;{part_to(num)}</span>
            <h3>{name}</h3>
            <p>{BLURB[num]}</p>
          </div>
        </div>''')

    faq = []
    for i, (q, a) in enumerate(FAQ, 1):
        faq.append(f'''        <div class="faq-item">
          <button class="faq-question" aria-expanded="false" aria-controls="faq{i}">
            {q}
          </button>
          <div class="faq-answer" id="faq{i}" hidden>
            <p>{a}</p>
          </div>
        </div>''')

    sm = "\n".join(f'''          <article class="testimonial-item amostra-item" role="listitem">
            <img src="./anteprime/{f}.webp" alt="{alt}" width="1100" height="{hh}" loading="lazy" decoding="async">
          </article>''' for f, alt, hh in SAMPLES)

    # Le testimonianze sono quelle che il sito ha gia': non se ne inventa
    # nessuna per l'odontoiatria, e non se ne scrive una nuova.
    testi = "\n".join(
        f'          <article class="testimonial-item" role="listitem">'
        f'<img src="./depoimentos/testimonio-{i}.webp" alt="Feedback and '
        f'reviews from healthcare professionals using MedStudyLab" '
        f'width="1254" height="1254" loading="lazy" decoding="async">'
        f'</article>' for i in range(1, 14))

    ico_lock = ('<svg aria-hidden="true" focusable="false" class="lc" '
                'viewBox="0 0 24 24" fill="none" stroke="currentColor" '
                'stroke-width="2" stroke-linecap="round" '
                'stroke-linejoin="round"><rect width="18" height="11" x="3" '
                'y="11" rx="2" ry="2"/><path d="M7 11V7a5 5 0 0 1 10 0v4"/>'
                '</svg>')
    nav = lambda t, d, lab, pts: (
        f'<button type="button" class="carousel-nav" data-dir="{d}" '
        f'data-target="{t}" aria-label="{lab}"><svg viewBox="0 0 24 24" '
        f'fill="none" stroke="currentColor" stroke-width="2.4" '
        f'stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'
        f'<polyline points="{pts}"></polyline></svg></button>')
    P, N = "15 18 9 12 15 6", "9 18 15 12 9 6"

    # Il footer e' quello delle altre landing del sito, con una sola
    # differenza: fra i link c'e' un &middot;, e non il margin-left da 8px.
    # Con il margine i cinque link uscivano dalla pagina a 390 px e
    # comparivano le barre di scorrimento orizzontali — e' lo stesso
    # inciampo che avevano le landing di studiofacile.
    link = ('color: rgba(255,255,255,0.7); text-decoration: underline;')
    footer_links = (f'<a href="/refund-policy" style="{link}">Refund Policy</a>'
                    f' &middot; <a href="/privacy" style="{link}">Privacy</a>'
                    f' &middot; <a href="/terms" style="{link}">Terms</a>'
                    f' &middot; <a href="/support" style="{link}">Support</a>'
                    f' &middot; <a href="https://catalog.medicalstudylab.com/"'
                    f' style="{link}" target="_blank" rel="noopener">All '
                    f'products</a>')

    return f'''<body>

  <!-- OFFER BANNER -->
  <div class="promo" role="status" aria-live="off">
    <div class="promo-in">
      <span class="promo-txt">Launch Offer</span>
      <span class="promo-time">Valid until today, <span class="promo-clock" id="promoClock"></span></span>
    </div>
  </div>

  <!-- HERO -->
  <section class="hero">
    <div class="hero-content">
      <div class="hero-mockup">
        <img src="./mockups/{SLUG}/hero.webp" alt="{TITLE}, with {B1} and {B2} as bonus books"
             width="1200" height="886" loading="eager" fetchpriority="high" decoding="async">
      </div>
      <p class="hero-social">
        <span class="stars" aria-hidden="true">★★★★★</span>
        <span><strong>+11,978 students &amp; healthcare professionals</strong></span>
      </p>
      <h1>The Easiest Way to Understand Dentistry <mark>Explained Entirely with Drawings!</mark></h1>
      <p class="subheadline">From a tooth in cross-section to the sterilization chain: {PAGES} illustrated pages, one topic per page &mdash; written for the people beside the chair, so you understand what is happening and know what to set out. Dental assistants, hygienists and first-year students.</p>
      <a href="#offer" id="cta-hero" class="btn-cta">I WANT TO UNDERSTAND DENTISTRY WITH DRAWINGS</a>
      <p class="cta-small-print">
        {ico_lock} Digital book (PDF) · US edition · Secure checkout · Instant download · 30-day guarantee
      </p>
    </div>
  </section>

  <!-- STATS BAR -->
  <section class="stats-bar">
    <div class="container">
      <div class="stats-grid">
        <div class="stat-item">
          <div class="icon"><svg aria-hidden="true" focusable="false" class="lc" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M17 10c.7-.7 1.69 0 2.5 0a2.5 2.5 0 1 0 0-5.5A2.5 2.5 0 1 0 14 2.5c0 .81.7 1.8 0 2.5l-9 9c-.7.7-1.69 0-2.5 0a2.5 2.5 0 0 0 0 5.5A2.5 2.5 0 1 0 10 21.5c0-.81-.7-1.8 0-2.5Z"/></svg></div>
          <strong>One topic per page</strong>
          <p>the drawing carries the logic, the text is the caption</p>
        </div>
        <div class="stat-item">
          <div class="icon"><svg aria-hidden="true" focusable="false" class="lc" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M4 19.5v-15A2.5 2.5 0 0 1 6.5 2H20v20H6.5a2.5 2.5 0 0 1 0-5H20"/></svg></div>
          <strong>{PAGES} illustrated pages</strong>
          <p>{N_PARTS} parts and {N_CHAP} chapters, from the teeth to sterilization</p>
        </div>
        <div class="stat-item">
          <div class="icon"><svg aria-hidden="true" focusable="false" class="lc" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"/><path d="M12 2a14.5 14.5 0 0 0 0 20 14.5 14.5 0 0 0 0-20"/><path d="M2 12h20"/></svg></div>
          <strong>All three numbering systems</strong>
          <p>charted in Universal, with FDI and Palmer side by side</p>
        </div>
      </div>
    </div>
  </section>

  <!-- PREVIEWS -->
  <section class="section" aria-label="Sample pages">
    <div class="container">
      <h2 class="text-center">Here's What the Pages You'll Study Look Like</h2>
      <p class="text-center section-sub-p">One topic per page, the drawing that carries the logic and the text that captions it. Look inside:</p>

      <div class="testimonials-carousel-wrap" role="region" aria-label="Sample pages carousel">
        {nav("amostras-scroll", "prev", "Previous page", P)}
        {nav("amostras-scroll", "next", "Next page", N)}
        <div class="testimonials-scroll" id="amostras-scroll" role="list" data-no-autoplay>
{sm}
        </div>
        <div class="carousel-progress" aria-hidden="true"><div class="carousel-progress-inner" id="amostras-progress"></div></div>
        <div class="carousel-dots" id="amostras-dots" role="tablist" aria-label="Navigation"></div>
      </div>
    </div>
  </section>

  <!-- TESTIMONIALS -->
  <section class="section section-alt section-snug-top" aria-label="Reviews">
    <div class="container">
      <h2 class="text-center" style="margin-bottom: 32px;">What Over 11,978+ Students and Professionals Using MedStudyLab Have to Say:</h2>

      <div class="testimonials-carousel-wrap" role="region" aria-label="Reviews carousel">
        {nav("testimonials-scroll", "prev", "Previous review", P)}
        {nav("testimonials-scroll", "next", "Next review", N)}

        <div class="testimonials-scroll" id="testimonials-scroll" role="list">
{testi}
        </div>

        <div class="carousel-progress" aria-hidden="true">
          <div class="carousel-progress-inner" id="testimonials-progress"></div>
        </div>

        <div class="carousel-dots" id="testimonials-dots" role="tablist" aria-label="Reviews navigation"></div>
      </div>
    </div>
  </section>

  <!-- WHY IT IS DRAWN -->
  <section class="section section-alt section-snug-top">
    <div class="container">
      <h2 class="text-center">Why One Drawing Explains What Three Pages of Text Don't</h2>
      <div class="solution-content">
        <p class="text-center">Dental textbooks exist and they are good. The problem is not that the information is missing: it is that it arrives in blocks of text, and a week later almost none of it is left.</p>
        <p class="text-center">Here every topic sits on <strong>a single page, with the drawing doing the work</strong> and the text captioning it.</p>
        <div class="solution-image">
          <img src="./anteprime/dentistry_02.webp" alt="A tooth in cross-section: enamel, dentin, pulp, and decay crossing them one layer at a time" width="1100" height="1473" loading="lazy" decoding="async">
        </div>
        <p class="text-center">This is the page on the tooth. It is drawn in cross-section, and underneath it are the four stages of decay: enamel, dentin, pulp, apex. <strong>Looking at it answers, on its own, the question every patient asks</strong>: why a cavity doesn't hurt at first and then suddenly does.</p>
        <p class="text-center">Because enamel has no nerves, and the pain starts in the dentin. One drawing, and you don't forget it. That is what the book does for {N_CHAP} topics.</p>
        <p class="text-center" style="font-size: 22px; font-weight: 700; margin-top: 40px;">First you understand it. Only then does remembering it matter.</p>
      </div>
    </div>
  </section>

  <!-- COMPARISON -->
  <section class="comparison-section fade-in visible" aria-label="A list of names versus an illustrated page">
    <div class="container">
      <div class="section-header">
        <span class="eyebrow">The Difference Is Visual</span>
        <h2>Stop studying walls of text you forget in three days:</h2>
      </div>
      <div class="comparison-grid">
        <div class="comparison-card bad-card">
          <div class="comparison-label bad">ALL TEXT</div>
          <ul class="comparison-bullets bad-list">
            <li>Pages of prose to commit to memory</li>
            <li>No drawings, no context</li>
            <li>You still freeze in the operatory</li>
          </ul>
          <img src="./mockups/{SLUG}/questo.webp" alt="Pages of text to learn by heart" width="900" height="1190" loading="lazy" decoding="async">
        </div>
        <div class="comparison-card good-card">
          <div class="comparison-label good">THIS BOOK</div>
          <ul class="comparison-bullets good-list">
            <li>The same things, but drawn</li>
            <li>One topic per page, with its own logic</li>
            <li>You remember it because you understood it</li>
          </ul>
          <img src="./anteprime/dentistry_01.webp" alt="Tooth numbering explained by quadrant in the Universal system" width="1100" height="1557" loading="lazy" decoding="async">
        </div>
      </div>
    </div>
  </section>

  <!-- CONTENTS -->
  <section class="subjects-section fade-in visible" aria-label="Table of contents">
    <div class="container">
      <div class="section-header">
        <span class="eyebrow eyebrow-inverse">Table of Contents</span>
        <h2>Take a Look at the {N_PARTS} Parts and {N_CHAP} Chapters</h2>
        <p class="subjects-subtitle">Twenty pages on the teeth alone, then instruments, materials and sterilization, plus four pull-out tables: {PAGES} pages, all illustrated</p>
      </div>
      <div class="subjects-accordion fade-in visible" role="list">
{chr(10).join(acc)}
      </div>
    </div>
  </section>

  <!-- SOLUTION -->
  <section class="section section-alt">
    <div class="container">
      <h2 class="text-center">What If Every Topic Fit on a Single Page?</h2>
      <div class="solution-content">
        <p class="text-center">Picture this:</p>
        <p class="text-center">Instead of reading three pages of text on how a tooth is built...</p>
        <p class="text-center">...you see it drawn in cross-section, <strong>with its layers and the decay crossing them one at a time</strong>. The same for the names, the numbers, the materials and sterilization: one topic, one page, one drawing.</p>
        <div class="solution-image">
          <img src="./anteprime/dentistry_07.webp" alt="Where the nerves run, and why anesthetic takes here and not there" width="1100" height="1473" loading="lazy" decoding="async">
        </div>
        <p class="text-center">You stop <strong>memorizing and start understanding</strong>. And once you have seen why a lower block numbs half the face and an upper injection doesn't, you never have to remember it again.</p>
        <p class="text-center" style="font-size: 22px; font-weight: 700; margin-top: 40px;">That's exactly what {TITLE} is.</p>
        <p class="text-center">It isn't &ldquo;one more PDF&rdquo;. It's <strong>{N_PARTS} parts and {N_CHAP} illustrated chapters</strong>: the teeth, the instruments, the materials and infection control &mdash; and at the end, <strong>four tables made to be printed</strong>.</p>
        <p class="text-center">Because what the brain sees organized, <strong>it remembers</strong>.</p>
      </div>
    </div>
  </section>

  <!-- MODULES -->
  <section class="section">
    <div class="container">
      <h2 class="text-center">Here's What You Get With {TITLE}:</h2>
      <div style="margin: 20px auto 28px;">
        <img src="./mockups/{SLUG}/combo.webp" alt="{TITLE}: mockup with sample pages" width="1100" height="1620" loading="lazy" decoding="async" style="max-width: 480px; width: 100%; display: block; margin: 0 auto;">
      </div>
      <div class="topics-grid">
{chr(10).join(topics)}
      </div>
      <p class="text-center" style="font-size:15px;color:var(--text-light);max-width:760px;margin:0 auto;">
        At the end: <strong>four pull-out tables made to be printed</strong> &mdash; the three
        numbering systems side by side, the four trays, the setting and working times, and
        the whole infection control chain.
      </p>
      <div style="text-align: center; margin-top: 48px;">
        <a href="#offer" class="btn-cta">I WANT TO SEE THE FULL OFFER</a>
      </div>
    </div>
  </section>

  <!-- VALUE STACK -->
  <section class="value-section">
    <div class="container">
      <h2 class="text-center">But That's Not All: You Also Get 2 Bonus Books</h2>

      <div class="bonus-grid">
        <div class="bonus-item-with-image">
          <div class="bonus-mockup">
            <img src="./mockups/{SLUG}/bonus-trays.webp" alt="{B1}, the bonus with 16 procedures" width="720" height="1000" loading="lazy" decoding="async">
          </div>
          <div class="bonus-text">
            <h3>BONUS 1: &ldquo;{B1}&rdquo;, 16 procedures from the schedule</h3>
            <p class="value">Standalone value: {VAL_B1}</p>
            <p>20 pages, <strong>one tray per page</strong>: from the exam and the prophy to the surgical extraction, from the anterior composite to the crown cementation and the pediatric crown.</p>
            <p style="margin-top: 12px;">The main book teaches you to recognize. This one you open in the morning, look at the schedule, and set up: every tray is already drawn in the order it gets used, with a pull-out chart that puts all sixteen on one sheet.</p>
          </div>
        </div>

        <div class="bonus-item-with-image">
          <div class="bonus-mockup">
            <img src="./mockups/{SLUG}/bonus-emerg.webp" alt="{B2}, the bonus with 10 situations" width="720" height="1000" loading="lazy" decoding="async">
          </div>
          <div class="bonus-text">
            <h3>BONUS 2: &ldquo;{B2}&rdquo;, 10 situations</h3>
            <p class="value">Standalone value: {VAL_B2}</p>
            <p>20 pages on what happens when the appointment goes off script: <strong>syncope, low blood sugar, allergic reaction, asthma attack</strong>, seizure, airway obstruction, bleeding, chest pain, hyperventilation and stroke.</p>
            <p style="margin-top: 12px;">Every page has the same three bands in the same order: how you recognize it, what you do first, and what you never do. The role stays yours &mdash; recognize, call, assist.</p>
          </div>
        </div>
      </div>

      <!-- DECISION BOX -->
      <div class="decision-box" id="offer">
        <img src="./mockups/{SLUG}/hero.webp" alt="{TITLE} with the two bonus books" class="db-mockup" width="1200" height="886" loading="lazy" decoding="async">
        <h3 class="db-title">{KIT}: {TITLE} + 2 Bonus Books</h3>
        <ul class="db-checklist">
          <li>{CHECK_SVG}{TITLE}: {PAGES} illustrated pages<span class="db-price-val">{VAL_MAIN}</span></li>
          <li>{CHECK_SVG}Bonus 1: {B1}<span class="db-price-val">{VAL_B1}</span></li>
          <li>{CHECK_SVG}Bonus 2: {B2}<span class="db-price-val">{VAL_B2}</span></li>
          <li>{CHECK_SVG}High-resolution printable PDFs<span class="db-price-val">Included</span></li>
        </ul>
        <div class="db-anchoring">
          <p class="db-old-price">Total value: {TOTAL}</p>
          <p class="db-new-price-label">Today only:</p>
          <p class="db-new-price">{PRICE}</p>
          <span class="db-discount-badge">YOU SAVE {SAVINGS}</span>
        </div>
        <a href="{CHECKOUT}" data-checkout class="db-cta">YES, I WANT THE {KIT.upper()} FOR {PRICE}</a>
        <div class="db-trust">
          <span class="db-trust-item"><span class="db-trust-icon"><svg viewBox="0 0 24 24"><path d="M12 1L3 5v6c0 5.55 3.84 10.74 9 12 5.16-1.26 9-6.45 9-12V5l-9-4z"/></svg></span>Secure purchase</span>
          <span class="db-trust-item"><span class="db-trust-icon"><svg viewBox="0 0 24 24"><path d="M18 8h-1V6c0-2.76-2.24-5-5-5S7 3.24 7 6v2H6c-1.1 0-2 .9-2 2v10c0 1.1.9 2 2 2h12c1.1 0 2-.9 2-2V10c0-1.1-.9-2-2-2zm-6 9c-1.1 0-2-.9-2-2s.9-2 2-2 2 .9 2 2-.9 2-2 2zm3.1-9H8.9V6c0-1.71 1.39-3.1 3.1-3.1s3.1 1.39 3.1 3.1v2z"/></svg></span>Encrypted payment</span>
          <span class="db-trust-item"><span class="db-trust-icon"><svg viewBox="0 0 24 24"><path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm-2 15l-5-5 1.41-1.41L10 14.17l7.59-7.59L19 8l-9 9z"/></svg></span>30-day guarantee</span>
        </div>
        <p class="db-small-print">Digital book (PDF), instant download. All 3 books arrive by email right after purchase. One-time payment, no installments or hidden fees.</p>
      </div>
    </div>
  </section>

  <!-- WHO IS IT FOR -->
  <section class="section">
    <div class="container">
      <h2 class="text-center">Is This Material Right for You?</h2>
      <div class="paraquem-grid">
        <div class="paraquem-card">
          <img class="paraquem-foto" src="./img/persona-student.webp" alt="A student in a dental program" loading="lazy" width="900" height="672">
          <div class="paraquem-info">
            <h3>You're studying dental assisting or hygiene</h3>
            <p>You have the textbooks, so information isn't what you're short of: seeing it is. Here every topic sits on one page, with the drawing carrying the logic and the text captioning it.</p>
          </div>
        </div>
        <div class="paraquem-card">
          <img class="paraquem-foto" src="./img/persona-professional.webp" alt="A dental assistant working chairside" loading="lazy" width="900" height="672">
          <div class="paraquem-info">
            <h3>You're already chairside, and nobody drew it for you</h3>
            <p>You set the trays and you pass the instruments. What you never got shown is what is underneath: the layers decay crosses, where the nerves run, and why the rinse-and-dry step is the one that ruins instruments.</p>
          </div>
        </div>
        <div class="paraquem-card">
          <img class="paraquem-foto" src="./img/persona-graduate.webp" alt="Someone newly started in a dental office" loading="lazy" width="900" height="672">
          <div class="paraquem-info">
            <h3>You just started in an office</h3>
            <p>You follow what's happening but you don't have the names yet, and every time one gets called out you have to look at the tray. You need the whole picture and the tables you can keep in front of you.</p>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- AUTHOR -->
  <section class="section author-section">
    <div class="container">
      <h2 class="text-center">Who's Behind Med Study Lab</h2>
      <div class="author-content">
        <div class="author-image">
          <img src="./Img-Leandro.webp" alt="Leandro Moretti - Pharmacist and founder of Med Study Lab" width="266" height="400" loading="lazy" decoding="async">
        </div>
        <div class="author-bio">
          <h3>Leandro Moretti</h3>
          <h4>Pharmacist · Founder of Med Study Lab</h4>
          <p>Pharmacist and founder of Med Study Lab, the series of illustrated books for healthcare: pharmacology, clinical handbooks, lab tests, EKGs, dosage calculations, clinical anatomy and now dentistry.</p>
          <p>The method is always the same: <strong>visual clarity and one topic per page</strong>, because what the brain sees organized, it remembers.</p>
          <p>For dentistry the decision was a different one: <strong>not to write one more textbook for the dentist</strong>. Those already exist. What doesn't exist is the book written for the people next to the dentist, who have to recognize, set up and stay a step ahead &mdash; and this is that book.</p>
        </div>
      </div>
    </div>
  </section>

  <!-- RECAP -->
  <section class="section section-alt">
    <div class="container">
      <h2 class="text-center">To Recap: Here's Everything You Get</h2>
      <ul class="recap-list">
        <li>{TITLE}: {PAGES} illustrated pages in {N_PARTS} parts &mdash; the teeth and all three numbering systems, the instruments and the trays, the materials and their setting times, and the infection control chain on CDC and OSHA lines</li>
        <li>Bonus 1: &ldquo;{B1}&rdquo;, 20 pages and 16 procedures, one tray per page (value {VAL_B1})</li>
        <li>Bonus 2: &ldquo;{B2}&rdquo;, 20 pages and 10 situations (value {VAL_B2})</li>
        <li>Four pull-out tables made to be printed and taped up next to the sterilizer</li>
        <li>Delivery: all 3 books by email right after purchase</li>
        <li>30-day guarantee: if it doesn't help, I refund you</li>
        <li>High-resolution PDFs: print them, annotate them, keep them in the operatory</li>
      </ul>
      <div class="price-recap">
        <p class="old-price">{TOTAL}</p>
        <p class="new-price">{PRICE}</p>
      </div>
      <div style="text-align: center;">
        <a href="#offer" class="btn-cta">I WANT TO SEE THE FULL OFFER</a>
      </div>
    </div>
  </section>

  <!-- GUARANTEE -->
  <section class="section">
    <div class="container">
      <div class="guarantee-box">
        <div class="icon"><svg aria-hidden="true" focusable="false" class="lc" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z"/><path d="m9 12 2 2 4-4"/></svg></div>
        <h3>&ldquo;Risk-Free Trial&rdquo; Guarantee: 30 Days</h3>
        <p>You have 30 full days to try {TITLE} and the two bonus books.</p>
        <p>If in that time the material didn't help you, didn't get used or simply wasn't what you expected, <strong>I refund 100% of what you paid</strong>.</p>
        <p>No questions. No fine print. No hassle.</p>
        <p><strong>The risk is ZERO. The decision is yours.</strong></p>
      </div>
    </div>
  </section>

  <!-- FAQ -->
  <section class="section section-alt">
    <div class="container">
      <h2 class="text-center">Frequently Asked Questions</h2>
      <div class="faq-container">
{chr(10).join(faq)}
      </div>
    </div>
  </section>

  <!-- FINAL CTA -->
  <section class="final-cta">
    <div class="container">
      <h2>One Last Thing Before You Decide...</h2>
      <p>Chairside, you don't have to learn it by getting it wrong first.</p>
      <p>You don't have to memorize fifty shapes without ever being told why they are shaped that way.</p>
      <p>And you certainly <strong>shouldn't find out you can't read a tray at the moment you need to</strong>.</p>
      <p style="font-size: 22px; font-weight: 700; margin-top: 32px;">There's an easier way. And it's one click away.</p>
      <p>{N_PARTS} parts, {N_CHAP} illustrated chapters, four pull-out tables and two bonus books.</p>
      <p><strong>Now it's your turn.</strong></p>
      <div class="cta-summary">
        <ul>
          <li>One-time payment: {PRICE}</li>
          <li>Guarantee: 30 days</li>
          <li>Delivery: all 3 books right after purchase</li>
        </ul>
      </div>
      <a href="#offer" class="btn-cta">I WANT THE {KIT.upper()} FOR {PRICE}</a>
      <p class="cta-small-print" style="margin-top: 24px;">
        <svg aria-hidden="true" focusable="false" class="lc" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect width="14" height="20" x="5" y="2" rx="2" ry="2"/><path d="M12 18h.01"/></svg> Digital book (PDF) · The books arrive by email within minutes
      </p>
    </div>
  </section>

  <!-- FOOTER -->
  <footer class="footer">
    <div class="container">
      <p>© 2026 Med Study Lab · All rights reserved · {footer_links}</p><p class="legal-entity" style="margin:12px 0 0;font-size:10.5px;line-height:1.7;letter-spacing:.12em;opacity:.5;">QUILLSTONE DIGITAL LLC<br>1057 NW 136TH AVE, MIAMI, FL 33182</p>
    <p style="margin:10px 0 0;font-size:11px;opacity:.55;">Illustrated study material for the people who work beside the chair. It does not replace professional training, your state's scope-of-practice rules, your office's written protocols or the dentist's clinical judgment.</p>
    </div>
  </footer>
'''


def tail(tpl_tail):
    """Gli script dell'index, col prodotto e il prezzo di questa pagina.

    Il nome del prodotto nella misurazione e' quello del KIT, non del volume
    principale: in Meta e in GA4 deve corrispondere alla riga del checkout,
    altrimenti l'acquisto e la visita finiscono su due prodotti diversi."""
    t = tpl_tail
    rep = [('"item_id": "ekg", "item_name": "Reading EKGs Made Visual", '
            '"price": 27', f'"item_id": "{SLUG}", "item_name": "{KIT}", '
                           f'"price": {PRICE_N}'),
           ('"content_ids": ["ekg"], "content_name": "Reading EKGs Made '
            'Visual", "content_type": "product", "value": 27',
            f'"content_ids": ["{SLUG}"], "content_name": "{KIT}", '
            f'"content_type": "product", "value": {PRICE_N}')]
    for a, b in rep:
        assert a in t, a
        t = t.replace(a, b)
    t = t.replace("value: 27,", f"value: {PRICE_N},")
    return t


def main():
    src = open(os.path.join(SITO, "ekg.html"), encoding="utf-8").read()
    i = src.index("<body>")
    j = src.index("  <!-- Dynamic Offer Date")
    out = head(src[:i]) + body() + tail(src[j:])
    open(os.path.join(SITO, f"{SLUG}.html"), "w", encoding="utf-8",
         newline="\n").write(out)
    mancano = [p for p in
               [f"mockups/{SLUG}/{n}" for n in
                ("hero.webp", "combo.webp", "bonus-trays.webp",
                 "bonus-emerg.webp", "questo.webp", "og.jpg")]
               + [f"anteprime/{f}.webp" for f, _a, _h in SAMPLES]
               if not os.path.exists(os.path.join(SITO, p))]
    print(f"{SLUG}.html: {len(out)//1024} KB - {PAGES} pages, {N_PARTS} parts,"
          f" {N_CHAP} chapters - {PRICE} (value {TOTAL}, save {SAVINGS})")
    if mancano:
        print(f"  missing images: {len(mancano)} -> {mancano[:3]}")
    for tok in ("PLACEHOLDER",):
        if tok in out:
            print(f"  WARNING: {out.count(tok)} x {tok} still in the page")


if __name__ == "__main__":
    main()
